### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'attrToRemove' of undefined

### ISSUE THREAD

**Issue by pragmaproducts** [aurelia/ui-virtualization#109]
Get the top error when running virtual-repeat.for on a li

Usage:
```
<template>
    <ul>
        <li virtual-repeat.for="item of items">${item.description}</li>
    </ul>
</template>
```

packages:
```
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@2.1.1",
    "aurelia-framework": "npm:aurelia-framework@1.1.2",
    "aurelia-ui-virtualization": "npm:aurelia-ui-virtualization@1.0.0-beta.3.1.0",
```

main setup:
```
            .plugin(
                "aurelia-dialog",
                "aurelia-ui-virtualization"
            );
```

**Comment by AStoker** [comment]
@pragmaproducts, please reformat this to follow the [Issue Template](https://github.com/aurelia/ui-virtualization/blob/master/ISSUE_TEMPLATE.md).

Also, more details on the error would be helpful.

**Comment by caperavensoftware** [comment]
I'm submitting a bug report I'm submitting a feature request

Library Version: 1.0.0-beta.3.1.0
Please tell us about your environment:

Operating System: OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]

Node Version: 8.1

NPM Version: 5 +
JSPM 0.16.32
Browser: all Web Browser 
Language: all | ESNext

Current behavior:

Expected/desired behavior:
that i show s a list of items with out throwing errors

What is the expected behavior?
that i show s a list of items with out throwing errors

When binding to a array of 1000 items using repeat.for to render those items works fine.
When changing that to virtual-repeat.for throws this error

```
ERROR [app-router] TypeError: Cannot read property 'attrToRemove' of undefined
    at ViewCompiler._compileElement (aurelia-templating.js:2839)
    at ViewCompiler._compileNode (aurelia-templating.js:2548)
    at ViewCompiler._compileElement (aurelia-templating.js:2854)
    at ViewCompiler._compileNode (aurelia-templating.js:2548)
    at ViewCompiler._compileNode (aurelia-templating.js:2570)
    at ViewCompiler.compile (aurelia-templating.js:2517)
    at eval (aurelia-templating.js:3218)
    at <anonymous>
error	@	aurelia-logging-console.js:54
(anonymous)	@	aurelia-logging.js:44
processResult	@	aurelia-router.js:1831
(anonymous)	@	aurelia-router.js:1784
```

the code that executes this is 
```
<li virtual-repeat.for="item of items">${item.title}</li>
```

the plugin was installed using jspm and added as a plugin in min.js as per git readme page

viewmodel:
```
export class Longlist {
    @bindable items;

    constructor(eventAggregator) {
        this.eventAggregator = eventAggregator;
    }

    attached() {
        // initialize
        this.items = [];
        for(let i = 0; i < 1000; i++) {
            this.items.push({
                title: `Item ${i}`
            })
        }
    }

    detached() {
        // dispose
    }
}
```
View
```
<template>
    <ul style="width: 100%; height: 100%; overflow: auto">
        <li virtual-repeat.for="item of items">${item.title}</li>
    </ul>
</template>
```

**Comment by caperavensoftware** [comment]
You can close this item. I found the problem.
It was in the way the plugin was registered.

this is the problem
```
            .plugin(
                "aurelia-dialog",
                "aurelia-ui-virtualization"
            );
```
this solved the problem
```
        aurelia.use.plugin('aurelia-dialog');
        aurelia.use.plugin('aurelia-ui-virtualization');
```

**Comment by Alexander-Taran** [comment]
this one can be closed (-:

**Comment by Alexander-Taran** [comment]
@caperavensoftware thank you so much for reporting back your own solution

**Comment by ciriousjoker** [comment]
Why is this still open?

**Comment by Alexander-Taran** [comment]
@EisenbergEffect can be closed
