### ISSUE TITLE
During printing only a subset is actually printed

### ISSUE THREAD

**Issue by palktonderAtpowelno** [aurelia/ui-virtualization#67]
I have a long list of items being displayed using virtual-repeat. When I try to print the list a lot of pages are printed but only the first couple of pages show actual content, the rest is blank. When I go back to a normal repeat everything is printed.

**Comment by AStoker** [comment]
I'd imagine this is because the items that are not printing are not on the DOM (which is makes it virtual, it saves the DOM from potentially crippling amounts of elements), where as when you use the regular `repeat.for`, all the elements are in the DOM.

**Comment by martingust** [comment]
@palktonderAtpowelno Yes, that is correct what @AStoker wrote. Only whats in the DOM will get printed, if you need to print/render the entire list in the DOM you should use the standard repeat.

**Comment by palktonderAtpowelno** [comment]
Honestly, I had already half guessed the reason for this behavior, but that's really not the point. It can't be that we have to choose between performance or the ability to print. I can just picture myself trying to explain to my customers the technical reasons for not having both; they'd laugh in my face. I would expect the code to be able to detect that we are currently printing (or previewing) and fall back to standard repeat behavior in such a case. Since the performance expectations are not the same for printing as for screen this should not be a problem.

**Comment by AStoker** [comment]
@palktonderAtpowelno, if you provide your own kind of print dialog (or can hook into the browsers print dialog), it would be possible to use some binds to replace the virtual repeat with the standard repeat. But keep in mind, if you are using a virtual repeat because of performance issues, you will have performance issues when trying to print with the standard repeat. If the standard repeat takes 30 seconds to load up 100,000 DOM elements, then you're going to be waiting that long for the print to take place. If the DOM freezes because you're trying to render 300,000 elements, then you're going to freeze trying to print.
