### ISSUE TITLE
Scroll up to a specific item

### ISSUE THREAD

**Issue by florinspataru1** [aurelia/ui-virtualization#80]
Is there a way to scroll inside the list up to a specific item? I am building a contacts list and I want to use letter navigation functionality. So the user can scroll to a specific letter. Is this possible? how?

**Comment by AStoker** [comment]
While they're two separate issues, this is probably hooked with this issue: https://github.com/aurelia/ui-virtualization/issues/7

If we're able to preserve the scroll position, that means we need to be able to scroll _to_ a position, which is what this issue is.
Right now I don't believe this is supported. If you have any ideas on approaches for this, it would be greatly appreciated.

**Comment by jwahyoung** [comment]
@AStoker It's late and I'm awake because of Mountain Dew and some other stuff. However....in your case, since the virtual repeater works with a fixed height, it should be a matter of math; with a fixed height and an element at position `n`, we should be able to determine the scroll position. Essentially, this would be the same as using the `offsetTop` property of an element in the set, only we'd be calculating it programmatically since the elements are virtual.

Based on what I remember about how this works, this would just mean that we would set the spacer element (which drives the scrollbar) to the appropriate height, and load the correct models into the virtual repeat DOM elements. To do this, there could be a bindable attribute on the repeated element itself, perhaps - I'm not sure what the best implementation would be.

I would be interested in this myself as I'm working on a PDF custom element (http://jedd-ahyoung.com/aurelia-pdfjs-example) which I may try to migrate to the virtual-repeat methodology for improved performance.

**Comment by AStoker** [comment]
Yes @jedd-ahyoung, scrolling to a position should be trivial, and a simple PR would be awesome. :) 
The trouble will be when you start incorporating the infinite scrolling capability into there. If you want to scroll to a position that was part of, say, page 3 of infinite scrolling, you'd need some way to restore to that position. That's the part where ideas would be welcome. 
It's not impossible by any means, and it might just need to be that we pass additional information into the `getMore` callback to allow the user to know what page of data to get...

**Comment by AStoker** [comment]
@florinspataru1, is this still an issue for you?  
An approach that we use is just using math. If you know which element you need to scroll to, you know which element that is in your array of items. Assuming your elements all are static height (which is the assumption currently for the repeater), you can multiply the item height by the location of the element in the array. _Then_ you simply need to tell your scroll container to scroll to that height.  

Let me know if that doesn't work. Until then, @EisenbergEffect, I think we can close this one.

**Comment by will-moore** [comment]
Apologies, but how do you "tell your scroll container to scroll to that height" after the DOM has rendered? 
e.g. ```document.getElementById("myDIV").scrollTop = '500px'```
Would this go in a task / microTask in a taskQueue?
