### ISSUE TITLE
Infinite-Scroll not working with tables

### ISSUE THREAD

**Issue by hmarcelodn** [aurelia/ui-virtualization#86]
I'm submitting a bug report

Library Version: 1.0.0-beta.3.0.1
Please tell us about your environment:

Operating System: Windows Server

Node Version: 5.0.0

NPM Version: 3.5.2

JSPM: 0.16.35

Browser: all

Language: ECMA6

Current behavior:

I created a table with 20 items inside the observable array. The table is wrapper with 200pxs, just 2 are visibles. If I scroll down it is not calling my infinite-scroll function. At the begginning a call is made to the infinite-scroll method with the following information:

topIndex: -3
isAtBottom: true
isAtTop: true

Its weird.

Check my Template file:

![2016-09-19_1655](https://cloud.githubusercontent.com/assets/5897525/18646889/00546636-7e8a-11e6-90c1-ded62a685526.png)

Check my infinite-call method:

`infiniteCall(scrollContext){
        console.log('Infinite call!');
        console.log(scrollContext);
    }`

Check the error:

![1658](https://cloud.githubusercontent.com/assets/5897525/18646979/549cd890-7e8a-11e6-9112-b673db965f07.png)

Expected/desired behavior:

I want to call my infinite-scroll method when there is no more items in the list to repeat.

**Comment by AStoker** [comment]
You're most likely running up against the buffer at the start. 20 items are already in the DOM (most likely), so that's why it's called as soon as you scroll (in case you have a _very_ small page size, and you want to ping the server for more data).
Your expected behavior I believe is already happening.

**Comment by hmarcelodn** [comment]
@AStoker Thanks. It is not that clear for me.

What **topIndex: -3** means? How can I use such number to get more items? Is not that an **index >= 0** ?

If I have 10 items and I reached the end I want to know that my last element is 10 so I can fetch rows and skip 10 items from the results and get the range 10-20 for example.

**Comment by AStoker** [comment]
When you get something like -3, it's an initial state that really is just noise. If you're getting true for both isAtTop and isAtBottom, then you know that you're currently rendering every single element in your array. The top element is rendered at the top, and the bottom element is rendered at the bottom.
If you have 10 items in your items array, and this function gets called, then you know that you can now get items 11-20, because your item array has a length of 10.
