### ISSUE TITLE
Allow to specify an offset for Infinite-Scroll

### ISSUE THREAD

**Issue by lulumetro** [aurelia/ui-virtualization#95]
**I'm submitting a feature request**

* **Library Version:**
1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.6.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.45

* **Browser:**
all

* **Language:**
all

**Current behavior:**
The infinite-scroll-next handler is triggered when the list "isAtTop" or "isAtBottom", causing a non-fluid infinite scroll behavior.

**Expected/desired behavior:**

* **What is the expected behavior?**
To be able to set an offset value (number of items from the current first visible item to the first item of the underlying collection, or from the last visible to the total last), so that the infinite-scroll-next handler function is called before reaching the end of the list.

* **What is the motivation / use case for changing the behavior?**
The UX will be improved with a more fluent scrolling experience

**Comment by AStoker** [comment]
This is something that has been discussed before. The concept is to use "markers" in the array so that when a "marker" suddenly becomes visible, it's time to get more data. This should be easy enough to accomplish, such that when a calculated number of elements (based off the current height of the container) have been scrolled past (or there are only a certain number of elements left), we trigger the get more.  

Do you think you could make a PR for this?

**Comment by PeterWone** [comment]
This approach would be an improvement but it forces the user to load the entire list to get at the last page. It would be much more useful to virtualise the _model_.

What I want is a SparseKeyset class that contains (surprise!) a sparse keyset. By keyset I mean that each item has an Id and a Caption, and resolving the Id value to an actual object is out of scope for the list. By sparse, I mean that it has a nominal length corresponding to a completely resolved result, but it might only contain the first 100 items. 

This will cause the list length to scale to the actual size of the result making absolute navigation possible; you could move directly to the middle or the end using the list scrollbar.

This sort of navigation should trigger a list-navigation event. The vm's handler for this can then tell SparseKeyset to fetch data in that part of its logical space. This fetching might come to nothing if the data is already present in the required range of list indexes. Data would be fetched in pages, so probing for absence requires only one test at the start of each logical page.

Provide a hook 

```
<template>
  <div virtual-repeat.for="item of items" scroll="getMore">
    ${$index} ${item.Id} ${item.Caption}
  </div>
</template>
```

and I'll write the SparseKeyset. Perhaps this event already exists; I was trying to find it when I ran across this issue - because I intend to do the above.

ui-virtualizing might need to be modified to show placeholders when items are not yet loaded.

**Comment by Alexander-Taran** [comment]
I'll just leave it here
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

for when the time comes
https://caniuse.com/#feat=intersectionobserver

**Comment by bigopon** [comment]
the PR at #154 now gives this behavior with an offset of 5. Ideally it should be just work: meaning the number of offset is adjusted based on view port height and item height to ensure smooth experience. Also I'm not sure how to provide configuration syntax for it to be used together with virtual repeat.
